### ISSUE TITLE
Want to talk to you personal

### ISSUE THREAD

**Issue by SimonDanny50501** [Cat-Katze/gama-no-github#1]
Anyway you look pretty good in your profile

**Comment by Cat-Katze** [comment]
> Anyway you look pretty good in your profile

Tnku ;) 👍🏼

Do you have any social media? Youtube? LinkedIn? Instagram?
I wish follow you...

**Comment by SimonDanny50501** [comment]
I do have only WhatsApp 0599835850

**Comment by Cat-Katze** [comment]
> I do have only WhatsApp 0599835850

I try to send you a message, but your phone number is not available on whatsapp

**Comment by SimonDanny50501** [comment]
That's not true and if you don't mind sending me yours

**Comment by SimonDanny50501** [comment]
***@***.***

**Comment by SimonDanny50501** [comment]
Simondanny5050@gmail.com
